version: 0.2
phases:
 install:
   commands:
     - echo "Install phase"
 build:
   commands:
     - echo "Build phase"
artifacts:
 files:
   - appspec.yml
   - scripts/**/*
   - index.html
   - style.css
   - app.js
   - sample.json
   - README.md
 discard-paths: yes