version: 0.2
phases:
 install:
   commands:
     - echo "Skipping yum update"
 build:
   commands:
     - echo "Build step starts"
     - echo "You can put npm build or zip here"
artifacts:
 files:
   - '**/*'